/**
 * Remove the stock locations left behind by verification runs.
 *
 * Several suites create a location, exercise a flow and never remove it, so demo-client had
 * accumulated 30 of them -- "Test ST (TST-1788259431018)", "Upd WH (UWH-1788769348536)" and so
 * on -- against 2 real ones. The location picker is in the header of every page, so this is
 * thirty rows of noise in front of the two entries anybody actually wants.
 *
 * REFUSES anything still referenced. A location holding stock is not clutter, it is a place
 * where pieces are, and deleting it would erase inventory rows and the transactions that
 * explain them. Those are reported instead, by name and quantity, so the decision is a
 * person's. --force exists for when that person has decided.
 *
 *   npx tsx src/scripts/purge-test-locations.ts                    # dry run, this tenant's
 *   npx tsx src/scripts/purge-test-locations.ts --apply
 *   npx tsx src/scripts/purge-test-locations.ts --client=demo-client --apply
 */
import { prisma } from '../lib/prisma';

const APPLY = process.argv.includes('--apply');
const FORCE = process.argv.includes('--force');
const CLIENT = (process.argv.find(a => a.startsWith('--client=')) ?? '--client=demo-client').split('=')[1];

/**
 * The names the suites use, anchored and paired with a generated code.
 *
 * Deliberately narrow. A shop is perfectly entitled to call a real location "Test Store", so
 * the name alone is not enough -- the code must also be one of the `PREFIX-<timestamp>` forms
 * only a script produces.
 */
const TEST_NAME = /^(Test|Upd)\s+(ST|WH|Store|Warehouse)\b/i;
const TEST_CODE = /^(TST|TWH|UWH|TSTR)-\d{10,}$/i;

async function main() {
  console.log(`${APPLY ? 'REMOVING' : 'DRY RUN --'} test locations for ${CLIENT}${FORCE ? ' (--force: referenced ones included)' : ''}\n`);

  const locations = await prisma.stockLocation.findMany({
    where: { clientId: CLIENT },
    select: {
      id: true, name: true, code: true,
      _count: {
        select: {
          stocks: true, transactions: true, reservations: true,
          salesOrders: true, locationProfiles: true, stockCounts: true
        }
      }
    },
    orderBy: { createdAt: 'asc' }
  });

  const looksGenerated = (l: typeof locations[number]) => TEST_NAME.test(l.name) && TEST_CODE.test(l.code);
  const referenceCount = (l: typeof locations[number]) => Object.values(l._count).reduce((a, b) => a + b, 0);

  const candidates = locations.filter(looksGenerated);
  const kept = locations.filter(l => !looksGenerated(l));
  const empty = candidates.filter(l => referenceCount(l) === 0);
  const busy = candidates.filter(l => referenceCount(l) > 0);

  console.log(`${locations.length} locations: ${kept.length} real, ${candidates.length} generated by test runs`);
  console.log(`  ${empty.length} hold nothing, ${busy.length} still referenced\n`);

  console.log('Keeping (not generated by a test run):');
  kept.forEach(l => console.log(`  ${l.name} (${l.code})`));

  if (busy.length) {
    console.log(`\n${FORCE ? 'REMOVING' : 'Refusing'} ${busy.length} that still hold something:`);
    for (const l of busy) {
      const refs = Object.entries(l._count).filter(([, n]) => n > 0).map(([k, n]) => `${k}=${n}`).join(' ');
      console.log(`  ${l.name} (${l.code})  ${refs}`);
      const stocks = await prisma.inventoryStock.findMany({
        where: { locationId: l.id },
        select: { quantity: true, variant: { select: { sku: true, product: { select: { title: true, status: true } } } } }
      });
      stocks.forEach(s => console.log(`      ${s.quantity} x ${s.variant.sku} — ${s.variant.product?.title} [${s.variant.product?.status}]`));
    }
    if (!FORCE) {
      console.log('\n  Deleting these would erase those stock rows and the transactions that explain');
      console.log('  them. Pass --force only if that is what you mean.');
    }
  }

  const toRemove = FORCE ? candidates : empty;
  console.log(`\n${APPLY ? 'Removing' : 'Would remove'} ${toRemove.length}:`);
  toRemove.forEach(l => console.log(`  ${l.name} (${l.code})`));

  if (APPLY && toRemove.length) {
    const ids = toRemove.map(l => l.id);
    // Ordered by dependency, and each guarded: a table this environment does not have must
    // not stop the rest of the cleanup.
    await prisma.inventoryTransaction.deleteMany({ where: { locationId: { in: ids } } }).catch(() => {});
    await prisma.inventoryEvent.deleteMany({ where: { locationId: { in: ids } } }).catch(() => {});
    await prisma.inventoryAlert.deleteMany({ where: { locationId: { in: ids } } }).catch(() => {});
    await prisma.inventoryReservation.deleteMany({ where: { locationId: { in: ids } } }).catch(() => {});
    await prisma.variantLocationProfile.deleteMany({ where: { locationId: { in: ids } } }).catch(() => {});
    await prisma.inventoryStock.deleteMany({ where: { locationId: { in: ids } } }).catch(() => {});
    const removed = await prisma.stockLocation.deleteMany({ where: { id: { in: ids }, clientId: CLIENT } });
    console.log(`\nRemoved ${removed.count}.`);
  }
}

main().catch(e => { console.error(e?.message ?? e); process.exitCode = 1; }).finally(() => prisma.$disconnect());
